name: tfm-alexander-container-security
services:
  api:
    image: tfm-api:hardened
    cap_drop:
    - ALL
    cpus: 0.5
    mem_limit: 256m
    read_only: true
    security_opt:
    - no-new-privileges:true
  nginx:
    image: nginx:alpine
    depends_on:
    - api
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - target: 80
      published: '8080'
      host_ip: 127.0.0.1
      protocol: tcp
