name: Security

on:
  pull_request:
    branches:
      - main

jobs:
  container-security:
    name: Container Security

    permissions:
      actions: read
      contents: write
      statuses: write

    uses: Alexander-FB/tfm-alexander-security-pipeline/.github/workflows/container-security.yml@main
